$font = JetBrains Mono

general {
    hide_curose = true
}

# Re-Activate once fingerprint auth is working
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 #ms
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0)

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 1

    font_family = $font
    placeholder_text = input password...
    fail_text = $PAMFAIL$FPRINTFAIL

    check_text = Authenticating...

    dots_size = 0.4
    dots_spacing = 0.3
    dots_center = true

    hide_input = false

    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 95
    font_family = $font

    position = 0, 300
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%A, %d %B %Y"
    font_size = 22
    font_family = $font

    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = User: $USER
    font_size = 25
    font_family = $font

    position = 0, 100
    halign = center
    valign = center
}
