general {
    lock_cmd = pidof hyprlock || hyprlock -q --grace 5 # pidof checks if hyprlock is already running
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on

    inhibit_sleep = 3
}

# Step 1: Dim the screen 
listener {
    timeout = 150 #s == 2.5 minutes
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# Step 2: Lock the session
listener {
    timeout = 300 #s == 5 minutes
    on-timeout = loginctl lock-session
}

# Step 3: Activate hibernation
listener {
    timeout = 1800 #s == 30 minutes
    on-timeout = systemctl hibernate
}
